/**
 * ARCHITECTURE NOTE — Updated July 2026
 * 
 * Supabase is used ONLY for:
 * 1. Authentication: supabase.auth (sessions, tokens)
 * 2. File Storage: supabase.storage (trip-reviews bucket)
 * 3. Edge Functions: supabase.functions (email scanner)
 * 
 * ALL business data (leads, payments, reviews, expenses,
 * audit_logs, etc.) is now stored in MySQL via PHP backend.
 * 
 * Do NOT add supabase.from() calls for business data.
 * Use leadService, reviewService, or PHP endpoints instead.
 */

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta as any).env?.VITE_SUPABASE_URL || "https://rfdumlnkmfuacsznogzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = (import.meta as any).env?.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmZHVtbG5rbWZ1YWNzem5vZ3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA3NzYxMDUsImV4cCI6MjA5NjM1MjEwNX0.5VtSJ46jEgI8tlqXMWOXz8jvc68C__Suo1WgGJw_KIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
  }
});