// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vblqawjhipgswvbtggwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZibHFhd2poaXBnc3d2YnRnZ3d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTMyMzksImV4cCI6MjA2NjM2OTIzOX0.fi26K1rNelltr6NBgfa517NXOOgKWzg3XK54u6pIp44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);